// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8F0By1KuDDby4U2c3HS6e8x6YuXTNiTs',
    appId: '1:684733558116:web:9bed32aef32b2fa48c9e71',
    messagingSenderId: '684733558116',
    projectId: 'portfolio-a5c99',
    authDomain: 'portfolio-a5c99.firebaseapp.com',
    storageBucket: 'portfolio-a5c99.firebasestorage.app',
    measurementId: 'G-PHPWSM5D03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmcW7u2hbVlOeBuPflYvH0Opw69nS5_pE',
    appId: '1:684733558116:android:2d21d8811d5fa1878c9e71',
    messagingSenderId: '684733558116',
    projectId: 'portfolio-a5c99',
    storageBucket: 'portfolio-a5c99.firebasestorage.app',
  );
}
